version: '3.8'
name: salingtau-be-development

services:
  postgres:
    container_name: postgres
    build:
      dockerfile: Dockerfile
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=admin123
      - POSTGRES_DB=salingtau
      - AT_SECRET=access-secret
      - RT_SECRET=refresh-secret

  redis:
    container_name: redis
    image: redis:8.2.1
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:
  redis_data:
